### ISSUE TITLE
loss of xp on death

### ISSUE THREAD

**Issue by glougloudu77** [PolarFox27/JobsMod#22]
Good morning,
I realized that the system that allows you to keep the xp when you die does not work.

**Comment by PolarFox27** [comment]
Hi,
On which version did you find the bug ?
Thanks for pointing out this bug

**Comment by glougloudu77** [comment]
Good morning, I play in 1.18.2 with the latest version of the mod

**Comment by PolarFox27** [comment]
Ok thanks ! I will look at it.
Have a nice day !

**Comment by glougloudu77** [comment]
thanks

**Comment by PolarFox27** [comment]
The bug has been fixed ! You will soon be able to download version 1.18.2-3.0.3.1 on Curseforge to have the fix.
Have a very nice day !

**Comment by glougloudu77** [comment]
thank you for considering my bug report,
I take advantage of this discussion to propose some functionality

- make items display if they are blocked when hovering over them

Added a file to prevent players from placing a block (useful for blocking the use of mekanism factories for example)

- add a file to prevent players from interacting with certain blocks (once again for mekanism factories for example)

- merge the unlocked items in the list for the same level (for example, if you unlock the left click and the right click at level 5, it only appears once in the unlock menu

good luck in advance

**Comment by PolarFox27** [comment]
Thank you for your suggestions, they are really nice ! I added them in the issues list, I hope to implement them as soon as possible.
Have a nice day
