### ISSUE TITLE
Craft and cooking bug

### ISSUE THREAD

**Issue by Shykaruu** [PolarFox27/JobsMod#23]
When taking items for xp in the inventory and taking the item that has been baked or is crafted, which must be the same item as the one that has been baked or is crafted, you gain xp for all items taken with the mouse  and not just the baked or crafted items.

**Comment by PolarFox27** [comment]
Hi,
thanks for pointing out a bug ! I will need some more detailed information to fix it. Which version of the mod and Minecraft are you playing with ? Also, I did not fully understand your explanation, could you maybe explain it in more details and with some screenshots of the game if it is possible for you ? 
Thank you and have a nice day !

**Comment by Shykaruu** [comment]
Hi, basically, when I click on an item to retrieve it from an furnace or a crafting table, and I pick up several items with the mouse, xp will be counted for the item that's been baked and the items picked up with the mouse that aren't supposed to give xp. this is whith the version 1.12.2 of minecraft and the version Jobs-1.12.2-3.0.2.1. Thanks you and have a nice day !

**Comment by PolarFox27** [comment]
1.12.2 is a too old version, I will not work on it anymore. Don't hesitate to leave a comment on Curseforge if you have questions about more recent versions.
