### ISSUE TITLE
How to xp bug & miss icons

### ISSUE THREAD

**Issue by nastyshade** [PolarFox27/JobsMod#27]
hi !

I added a new job "wizard" and I added in xp_breaking.json this:
{
	"wizard":[
		{"block":"xo:xp_ore","xp":[2,2,2,2,2]},
		{"block":"minecraft:glowstone","xp":[2,2,2,2,2]},
		{"block":"minecraft:lit_redstone_ore","xp":[1,1,1,1,1]},
		{"block":"minecraft:nether_wart","xp":[1,1,1,1,1]},
		{"block":"minecraft:lapis_ore","xp":[1,1,1,1,1]}
	]
}

I get good experience when I break blocks, however in the "How to xp" interface it's bug:

- the nether wart icon is not displayed
- the lapis icon is replaced by ink sack

[https://imgur.com/a/LE57Fam](https://imgur.com/a/LE57Fam)

information version:
- MineCraft: 1.12.2
- Forge: 14.23.5.2860
- OptiFine: 1.12.2_HD_U_G5
- Jobs: 1.12.2-3.0.2.1

**Comment by PolarFox27** [comment]
Thank you for reporting this bug, I will look at it !

**Comment by PolarFox27** [comment]
1.12.2 is a too old version, I will not work on it anymore. Don't hesitate to leave a comment on Curseforge if you have questions about more recent versions.
