### ISSUE TITLE
how do you block crafts

### ISSUE THREAD

**Issue by glougloudu77** [PolarFox27/JobsMod#28]
Good morning, we are working on a server and to make progress slower we are developing a job system but we are stuck on how to block crafts, we saw that your mod did, and we would like to know how you manage to block them, we would be very grateful.
Thanks in advance

**Comment by PolarFox27** [comment]
Hi, I block crafts in not a very elegant way. I replace the Vanilla crafting GUI with my own custom GUI in which I can define rules for blocked crafts. If you find another way, I would be very interested to know it !
