### ISSUE TITLE
placing enchantments on reward items

### ISSUE THREAD

**Issue by FrozerYTB** [PolarFox27/JobsMod#33]
hello i'm using the mod in version 1.12.2 and i make custom rewards (pickaxe...) for the miner job only problem, i can't put enchantements on the tools, would anyone know how to do it?

**Comment by PolarFox27** [comment]
Hi, 1.12.2 is a too old version, I will not work on it anymore. Please don't hesitate to leave a comment on Curseforge if you have any questions about newer versions.
