### ISSUE TITLE
Some Suggestions/Ideas

### ISSUE THREAD

**Issue by Tyrius1** [PolarFox27/JobsMod#8]
### New Skills ### 
Defender: Gains experience by blocking attacks 
Lumberjack: Gains experience by cutting down trees
Archer: Gains experience by dealing damage with a bow
Fisherman: Gains experience based on the fish caught
Crafter: Gains experience when crafting (x) item. For a general crafting experience job.
Chief: Gains experience when cooking foods 
Marksmen: gains experience when dealing damage with modded guns

### Skill Additions ### 
Magician: Could also gain magic experience based on damage done when holding (x) item. (For when there are modded items like magic wands and such)

Block Break Requirement config - Prevents breaking x block till reaching x lvl in x skill

Item Use config - Prevents using/interacting/placing x item till reaching x lvl in x skill

Wear Requirement config - Prevents equipping x Armor until reaching x lvl in x skill

Weapon Requirement config - Prevents dealing damage with x Weapon until reaching x lvl in x skill

Tool Requirement config - Prevents using x Tool until reaching x lvl in x skill

### Potential Compatibilities ### 
Better Shields mod to give experience based on the damage absorbed to allow for better shields to yield better experience

CHAMPIONS mod to give more Hunter experience based on the tier of champion

Enhanced Celestials mod to give more Hunter/Defender experience during the Blood Moon event

Majruszs Difficulty mod to give more experience to all skills when increasing difficulty to Expert mode and Master Mode

### Potential Future Compatibilities ### 
Elementalcraft mod to give magic experience based on various features (Will provide further info in the future)

Occutlism mod to give magic experience based on various features (Will provide further info in the future)

Botania mod to give magic experience based on mana used when using various Botania blocks (Will provide further info in the future)

**Comment by PolarFox27** [comment]
Thanks for your suggestions ! I'm really interested in implementing the skill additions you propose, they will be available in future releases. I don't think I will be able do implement mod compatibilities, because the mod is already complex to use, and it offers already the possibility to gain xp using modded blocks and items.
